# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Dec  4 15:17:57 2024
# ------------------------------------------------

package:
  name: nest-asyncio
  version: 1.6.0
source:
  sha256: 6f172d5449aca15afd6c646851f4e31e02c598d553a667e38cafa997cfec55fe
  url: https://pypi.org/packages/source/n/nest_asyncio/nest_asyncio-1.6.0.tar.gz
build:
  noarch: python
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/nest-asyncio_1733325553580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - liblzma 5.6.3 hb9d3cd8_0
    - liblzma-devel 5.6.3 hb9d3cd8_0
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.0 hadc24fc_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.4.0 hb9d3cd8_0
    - pip 24.3.1 pyh8b19718_0
    - python 3.9.20 h13acc7a_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.6.0 pyhff2d567_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - xz 5.6.3 hbcc6ac9_0
    - xz-gpl-tools 5.6.3 hbcc6ac9_0
    - xz-tools 5.6.3 hb9d3cd8_0
  run:
    - python >=3.9
test:
  imports:
    - nest_asyncio
  requires:
    - python 3.9.*
about:
  description: 'By design asyncio does not allow its event loop to be nested.

    This presents a practical problem - when in an environment where the event loop
    is already running it''s impossible to run tasks and wait for the result.

    Trying to do so will give the error RuntimeError - This event loop is already
    running.

    The issue pops up in various environments, such as web servers, GUI applications
    and in Jupyter notebooks.

    This module patches asyncio to allow nested use of asyncio.run and loop.run_until_complete.

    '
  dev_url: https://github.com/erdewit/nest_asyncio
  doc_url: https://github.com/erdewit/nest_asyncio
  home: https://github.com/erdewit/nest_asyncio
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Patch asyncio to allow nested event loops
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241204.2.1
  recipe-maintainers:
    - SylvainCorlay
    - dhirschfeld
    - pavelzw
    - yehoshuadimarsky
  remote_url: https://github.com/conda-forge/nest-asyncio-feedstock
  sha: cd88383dcca0c4fe958a6328334f52d40ed63bd6
